version: '3'
services:
#  ui:
#    container_name: ui
#    build: ./ui
#    ports:
#     - "8080:8080"
  elasticsearch:
    image: elasticsearch
    hostname: localhost
    ports:
      - '9200:9200'

  rabbitmq:
    image: rabbitmq
    hostname: localhost
    ports:
      - '15672:15672'
      - '5672:5672'